#Q1 
SELECT PRODUCTS.PRODUCT_NAME, IFNULL(SUPPLIERS.SUPPLIER_NAME, 'YEARLY_TOTAL') , IFNULL(DATES.QUATER,'YEARLY_TOTAL'), IFNULL(DATES.MONTH, 'Quarter_Total')AS 'MONTH', SUM(SALES.TOTAL_SALE) AS TOTAL_SALES
FROM PRODUCTS, SALES, DATES, SUPPLIERS
WHERE PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID AND
SALES.DATE_ID= DATES.DATE_ID AND
SALES.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID AND
PRODUCTS.PRODUCT_NAME IS NOT NULL AND
SUPPLIERS.SUPPLIER_NAME IS NOT NULL
GROUP BY PRODUCTS.PRODUCT_NAME, SUPPLIERS.SUPPLIER_NAME, DATES.QUATER, DATES.MONTH with Rollup
ORDER BY PRODUCT_NAME, QUATER, MONTH
;

#Q1 --ALTERNATIVE
SELECT SUPPLIERS.SUPPLIER_ID, PRODUCTS.PRODUCT_ID, CASE WHEN DATES.QUATER ='1' THEN 'QUATER_1'
WHEN DATES.QUATER ='2' THEN 'QUATER_2'
WHEN DATES.QUATER ='3' THEN 'QUATER_3' 
WHEN DATES.QUATER ='4' THEN 'QUATER_4' END AS 'MONTH',
 SUM(SALES.TOTAL_SALE) AS total_sales FROM SALES,DATES, PRODUCTS,SUPPLIERS
 WHERE SALES.DATE_ID = DATES.DATE_ID 
 AND SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID AND 
 SALES.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID 
 GROUP BY SALES.SUPPLIER_ID, DATES.QUATER, SALES.PRODUCT_ID
 UNION ALL 
 SELECT SUPPLIERS.SUPPLIER_ID, PRODUCTS.PRODUCT_ID,DATES.MONTH, sum(SALES.TOTAL_SALE) AS total_sales FROM SALES,DATES, PRODUCTS,SUPPLIERS
  WHERE SALES.DATE_ID = DATES.DATE_ID 
 AND SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID AND 
 SALES.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
 GROUP BY SALES.SUPPLIER_ID,MONTH, SALES.PRODUCT_ID
 UNION ALL 
 SELECT SUPPLIERS.SUPPLIER_ID, PRODUCTS.PRODUCT_ID,"YEARLY_TOTAL", sum(SALES.TOTAL_SALE) AS total_sales FROM SALES,DATES, PRODUCTS,SUPPLIERS
  WHERE SALES.DATE_ID = DATES.DATE_ID 
 AND SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID AND 
 SALES.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
 GROUP BY SALES.SUPPLIER_ID, SALES.PRODUCT_ID
 
 ORDER BY PRODUCT_ID,SUPPLIER_ID,'MONTH';




#Q2
SELECT STORES.STORE_NAME, PRODUCTS.PRODUCT_NAME,  SUM(SALES.TOTAL_SALE) AS TOTAL_SALES
FROM PRODUCTS, STORES, SALES
WHERE  SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID  AND
SALES.STORE_ID = STORES.STORE_ID 

GROUP BY STORE_NAME, PRODUCT_NAME
ORDER BY STORE_NAME, PRODUCT_NAME
;


#Q3
SELECT PRODUCTS.PRODUCT_NAME, SUM(SALES.TOTAL_SALE) AS TOTAL_SALES
FROM SALES, PRODUCTS, DATES
WHERE SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID AND
SALES.DATE_ID = DATES.DATE_ID AND
DATES.WEEK_DAY IN ('SATURDAY', 'SUNDAY')
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 5
;

#Q4
SELECT PRODUCTS.PRODUCT_NAME, 
IFNULL(SUM(CASE WHEN DATES.QUATER = '1' THEN SALES.TOTAL_SALE END),'') as Q1, 
IFNULL(SUM(CASE WHEN DATES.QUATER = '2' THEN SALES.TOTAL_SALE END),'') as Q2, 
IFNULL(SUM(CASE WHEN DATES.QUATER = '3' THEN SALES.TOTAL_SALE END),'') as Q3, 
IFNULL(SUM(CASE WHEN DATES.QUATER = '4' THEN SALES.TOTAL_SALE END),'') as Q4
 FROM PRODUCTS, SALES, DATES WHERE
  PRODUCTS.PRODUCT_ID = SALES.PRODUCT_ID AND
  SALES.DATE_ID= DATES.DATE_ID AND
  DATES.YEAR = 2016
  GROUP BY PRODUCTS.PRODUCT_NAME, DATES.QUATER
  ORDER BY PRODUCT_NAME, DATES.QUATER
  ;


#Q5
SELECT SALES.PRODUCT_ID, PRODUCTS.PRODUCT_NAME, 
IFNULL(SUM(CASE WHEN DATES.QUATER = '1' or DATES.QUATER = '2' THEN SALES.TOTAL_SALE END),'') as FIRST_HALF, 
IFNULL(SUM(CASE WHEN DATES.QUATER = '3'  or DATES.QUATER = '4' THEN SALES.TOTAL_SALE END),'') as SEC_HALF, 
SUM(SALES.TOTAL_SALE) AS YEARLY_TOTAL

FROM PRODUCTS, DATES, SALES WHERE
SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID AND
SALES.DATE_ID = DATES.DATE_ID
AND DATES.YEAR = "2016"

GROUP BY SALES.PRODUCT_ID
ORDER BY SALES.PRODUCT_ID
;



#Q6
SELECT * FROM MASTERDATA WHERE PRODUCT_NAME = 'Tomatoes';


#Q7
#MYSQL does not has a materialized view  so have to make a simple view
DROP  view STOREANALYSIS;
CREATE view STOREANALYSIS AS

  SELECT STORES.STORE_ID, STORES.STORE_NAME, PRODUCTS.PRODUCT_ID, PRODUCTS.PRODUCT_NAME, sum(SALES.TOTAL_SALE) STORE_TOTAL_SALE FROM STORES, SALES, PRODUCTS WHERE
  STORES.STORE_ID = SALES.STORE_ID AND
  SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID
  GROUP BY STORES.STORE_ID, STORES.STORE_NAME, PRODUCTS.PRODUCT_ID, PRODUCTS.PRODUCT_NAME
  ORDER BY STORE_NAME, PRODUCT_NAME
;

SELECT * FROM STOREANALYSIS;